// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ReportBuilder50;

{ITE} {DFMFileType} {C\HUANGYL\LIB\MYLIB\RTObjInspector.dfm}
{ITE} {DFMFileType} {UAdjustCtrlFrame.dfm}
{ITE} {DFMFileType} {UAdjustCtrls.dfm}
{ITE} {DFMFileType} {UBasicPlugins.dfm}
{ITE} {DFMFileType} {UCopyChildren.dfm}
{ITE} {DFMFileType} {UCopyPlugins.dfm}
{ITE} {DFMFileType} {UDataBindings.dfm}
{ITE} {DFMFileType} {UHistory.dfm}
{ITE} {DFMFileType} {UImages.dfm}
{ITE} {DFMFileType} {ULinkColumns.dfm}
{ITE} {DFMFileType} {ULinkCtrls.dfm}
{ITE} {DFMFileType} {UMain.dfm}
{ITE} {DFMFileType} {UPlugin.dfm}
{ITE} {DFMFileType} {UQuickAdjustCtrls.dfm}
{ITE} {DFMFileType} {UQuickLinkCtrls.dfm}
{ITE} {DFMFileType} {UReportInspector.dfm}
{ITE} {DFMFileType} {USelection.dfm}
{ITE} {DFMFileType} {UToolForm.dfm}
{ITE} {DFMFileType} {vcl\PICEDIT.dfm}
{ITE} {RCFileType} {ReportBuilder50_DRC.rc}

{$R 'C\HUANGYL\LIB\MYLIB\RTObjInspector.dfm' ObjectInspector:TFrame}
{$R 'UAdjustCtrlFrame.dfm' faAdjustCtrls:TFrame}
{$R 'UAdjustCtrls.dfm' dlgAdjustCtrls:TForm}
{$R 'UBasicPlugins.dfm' RDSBasicPlugIns:TForm(RDSPlugIn)}
{$R 'UCopyChildren.dfm' dlgCopyChildren:TForm}
{$R 'UCopyPlugins.dfm' RDSCopyPlugIns:TForm(RDSPlugIn)}
{$R 'UDataBindings.dfm' fmDataBindings:TForm(ToolForm)}
{$R 'UHistory.dfm' fmHistory:TForm(ToolForm)}
{$R 'UImages.dfm' dmImages:TDataModule}
{$R 'ULinkColumns.dfm' dlgLinkColumns:TForm}
{$R 'ULinkCtrls.dfm' dlgLinkCtrls:TForm}
{$R 'UMain.dfm' ReportDesigner:TForm}
{$R 'UPlugin.dfm' RDSPlugIn:TDataModule}
{$R 'UQuickAdjustCtrls.dfm' fmQuickAdjustCtrls:TForm(ToolForm)}
{$R 'UQuickLinkCtrls.dfm' fmQuickLinkCtrls:TForm(ToolForm)}
{$R 'UReportInspector.dfm' ReportInspector:TForm(ObjectInspector)}
{$R 'USelection.dfm' fmSelection:TForm(ToolForm)}
{$R 'UToolForm.dfm' ToolForm:TForm}
{$R 'vcl\PICEDIT.dfm' PictureEditorDlg:TForm(Form)}
{$R 'ReportBuilder50_DRC.res' 'ReportBuilder50_DRC.rc'}

{$E CHS}

begin
end.