// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Bookviewer2;

{ITE} {DFMFileType} {UBookMan.dfm}
{ITE} {DFMFileType} {UBookmarkMan.dfm}
{ITE} {DFMFileType} {UMain.dfm}
{ITE} {DFMFileType} {C\HUANGYL\LIB\MYLIB\HYLAbout.dfm}
{ITE} {RCFileType} {Bookviewer2_DRC.rc}

{$R 'UBookMan.dfm' dlgBookMan:TForm}
{$R 'UBookmarkMan.dfm' dlgBookmarkMan:TForm}
{$R 'UMain.dfm' fmViewer:TForm}
{$R 'C\HUANGYL\LIB\MYLIB\HYLAbout.dfm' dlgAbout:TForm}
{$R 'Bookviewer2_DRC.res' 'Bookviewer2_DRC.rc'}

{$E CHS}

begin
end.